services:
  postgres:
    image: postgres:16
    container_name: inventory_erp_postgres
    environment:
      POSTGRES_DB: inventory_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: